server:
  port: 8762

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: Spring-Cloud-Api-Gateway
  cloud:
    gateway:
      routes:
        - id: movie-catalog-service
          uri: lb://Movie-Catalog-Service
          predicates:
          - Path=/catalog/**
          
        - id: movie-info-service
          uri: lb://Movie-Info-Service
          predicates:
          - Path=/movies/**
      
        - id: rating-data-service
          uri: lb://Rating-Data-Service
          predicates:
          - Path=/ratingsdata/**